# Generated by Django 4.1.1 on 2022-12-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderator', '0008_delete_prevqstns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papername', models.CharField(max_length=100, null=True)),
                ('addedby', models.CharField(max_length=100, null=True)),
                ('pdf', models.FileField(null=True, upload_to='pdf/')),
                ('approval', models.BooleanField(default=False, null=True)),
                ('addedon', models.TimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.courses')),
                ('sem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.semesters')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.universities')),
            ],
        ),
        migrations.CreateModel(
            name='Booklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.courses')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.book')),
                ('semname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.semesters')),
                ('universityname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.universities')),
            ],
        ),
    ]
