# Generated by Django 4.1.1 on 2022-12-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0008_delete_prevqstns'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='addedby',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='addedon',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='approval',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.courses'),
        ),
        migrations.AddField(
            model_name='book',
            name='papername',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='sem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.semesters'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdf/'),
        ),
    ]
