# Generated by Django 4.1.1 on 2022-12-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_book_addedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='examyear',
            field=models.DateField(null=True),
        ),
    ]
