# Generated by Django 4.1.1 on 2022-12-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0008_delete_prevqstns'),
        ('upload', '0003_book_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.courses')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.book')),
                ('semname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.semesters')),
                ('universityname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.universities')),
            ],
        ),
    ]
