# Generated by Django 4.1.1 on 2022-12-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_book_examyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='examyear',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
