# Generated by Django 4.1.1 on 2022-11-30 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papername', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universityname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestername', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.courses')),
            ],
        ),
        migrations.CreateModel(
            name='PrevQstns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('fileloc', models.FileField(upload_to='questions')),
                ('addedby', models.TextField()),
                ('addedon', models.TimeField(auto_now_add=True)),
                ('approval', models.BooleanField(default=False)),
                ('Paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.papers')),
            ],
        ),
        migrations.AddField(
            model_name='papers',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.semesters'),
        ),
        migrations.AddField(
            model_name='courses',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.universities'),
        ),
    ]
