# Generated by Django 4.1.1 on 2022-11-30 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevqstns',
            name='addedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
