# Generated by Django 4.1.1 on 2022-11-30 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0002_alter_prevqstns_addedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=50)),
                ('semname', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.courses')),
            ],
        ),
        migrations.AlterField(
            model_name='papers',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.type'),
        ),
        migrations.DeleteModel(
            name='Semesters',
        ),
    ]
