# Generated by Django 4.1.1 on 2022-11-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0004_semesters_alter_type_semname'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='courseName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.courses'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.semesters'),
        ),
    ]
