# Generated by Django 4.1.1 on 2022-11-30 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderator', '0005_papers_coursename_alter_papers_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prevqstns',
            name='Paper',
        ),
        migrations.AddField(
            model_name='prevqstns',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.courses'),
        ),
        migrations.AddField(
            model_name='prevqstns',
            name='papername',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prevqstns',
            name='sem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.semesters'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='coursename',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.universities'),
        ),
        migrations.AlterField(
            model_name='prevqstns',
            name='addedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prevqstns',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='semesters',
            name='semestername',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.courses'),
        ),
        migrations.AlterField(
            model_name='type',
            name='semname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.semesters'),
        ),
        migrations.AlterField(
            model_name='type',
            name='typename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='universities',
            name='universityname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Papers',
        ),
    ]
