# Generated by Django 4.1.1 on 2022-11-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0006_remove_prevqstns_paper_prevqstns_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
