# Generated by Django 4.1.1 on 2022-12-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0007_delete_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrevQstns',
        ),
    ]
